package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Eorder;

public interface EorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    int insert(Eorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    Eorder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    List<Eorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    int updateByPrimaryKey(Eorder record);
}