package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.EorderProduct;

public interface EorderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER_PRODUCT
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    int insert(EorderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EORDER_PRODUCT
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    List<EorderProduct> selectAll();
}