package lt.vu.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.EMAIL
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private String lastname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.EMAIL
     *
     * @return the value of PUBLIC.CUSTOMER.EMAIL
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.EMAIL
     *
     * @param email the value for PUBLIC.CUSTOMER.EMAIL
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @param lastname the value for PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
}