package lt.vu.mybatis.model;

public class EorderProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EORDER_PRODUCT.ORDERS_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Long ordersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EORDER_PRODUCT.PRODUCTS_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Long productsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EORDER_PRODUCT.ORDERS_ID
     *
     * @return the value of PUBLIC.EORDER_PRODUCT.ORDERS_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Long getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EORDER_PRODUCT.ORDERS_ID
     *
     * @param ordersId the value for PUBLIC.EORDER_PRODUCT.ORDERS_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setOrdersId(Long ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EORDER_PRODUCT.PRODUCTS_ID
     *
     * @return the value of PUBLIC.EORDER_PRODUCT.PRODUCTS_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Long getProductsId() {
        return productsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EORDER_PRODUCT.PRODUCTS_ID
     *
     * @param productsId the value for PUBLIC.EORDER_PRODUCT.PRODUCTS_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setProductsId(Long productsId) {
        this.productsId = productsId;
    }
}