package lt.vu.mybatis.model;

import java.util.Date;

public class Eorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EORDER.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EORDER.DATE
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EORDER.CUSTOMER_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EORDER.ID
     *
     * @return the value of PUBLIC.EORDER.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EORDER.ID
     *
     * @param id the value for PUBLIC.EORDER.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EORDER.DATE
     *
     * @return the value of PUBLIC.EORDER.DATE
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EORDER.DATE
     *
     * @param date the value for PUBLIC.EORDER.DATE
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EORDER.CUSTOMER_ID
     *
     * @return the value of PUBLIC.EORDER.CUSTOMER_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EORDER.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.EORDER.CUSTOMER_ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}