package lt.vu.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRODUCTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    private String productname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @return the value of PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @param price the value for PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRODUCTNAME
     *
     * @return the value of PUBLIC.PRODUCT.PRODUCTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRODUCTNAME
     *
     * @param productname the value for PUBLIC.PRODUCT.PRODUCTNAME
     *
     * @mbg.generated Sat Apr 12 14:32:24 EEST 2025
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }
}